-- supabase-setup.sql
-- Jalankan file ini di Supabase Dashboard > SQL Editor.
-- Tabel ini menyimpan hasil input warga, rekomendasi sistem, verifikasi manual admin, dan hasil akhir.

CREATE TABLE IF NOT EXISTS public.warga_pkh (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  nik TEXT NOT NULL,
  rt TEXT NOT NULL,
  umur INTEGER NOT NULL,
  penghasilan TEXT NOT NULL,
  tanggungan INTEGER NOT NULL,
  kondisi_rumah TEXT NOT NULL,
  aset_produktif TEXT NOT NULL,
  kendaraan TEXT NOT NULL,
  dtks TEXT NOT NULL,

  ibu_hamil BOOLEAN DEFAULT FALSE,
  balita BOOLEAN DEFAULT FALSE,
  anak_sekolah BOOLEAN DEFAULT FALSE,
  disabilitas BOOLEAN DEFAULT FALSE,

  score INTEGER NOT NULL,
  components TEXT,
  system_recommendation TEXT,
  manual_recommendation TEXT DEFAULT '',
  officer_note TEXT DEFAULT '',
  final_result TEXT DEFAULT 'Menunggu Verifikasi Manual',
  verified_by TEXT DEFAULT '',
  verified_at TEXT DEFAULT '',
  details TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Untuk demo skripsi: izinkan frontend membaca, menambah, mengubah, dan menghapus data.
-- Catatan serius: gunakan data dummy, jangan masukkan NIK asli pada hosting publik.
ALTER TABLE public.warga_pkh ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "demo_select_warga_pkh" ON public.warga_pkh;
DROP POLICY IF EXISTS "demo_insert_warga_pkh" ON public.warga_pkh;
DROP POLICY IF EXISTS "demo_update_warga_pkh" ON public.warga_pkh;
DROP POLICY IF EXISTS "demo_delete_warga_pkh" ON public.warga_pkh;

CREATE POLICY "demo_select_warga_pkh"
ON public.warga_pkh
FOR SELECT
TO anon
USING (true);

CREATE POLICY "demo_insert_warga_pkh"
ON public.warga_pkh
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "demo_update_warga_pkh"
ON public.warga_pkh
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

CREATE POLICY "demo_delete_warga_pkh"
ON public.warga_pkh
FOR DELETE
TO anon
USING (true);
